channels:
  - conda-forge
  - defaults
  - fastai
dependencies:
  - python >=3.8,<3.9
  - pip
  # BASICS
  - deon    # Data ethics checklist
  - numpy
  - scipy
  - pandas
  # JUPYTER - LAB, NOTEBOOK, IPYKERNEL
  - jupyterlab 
  - ipykernel
  # OTHER
  - httpx
  - rich
  - scrapy
  - requests
  - streamlit
  - selenium
  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - sphinx
  - recommonmark
  - pip:
    - rich[jupyter]
